### ISSUE TITLE
No user error message displayed

### ISSUE THREAD

**Issue by austinmroczek** [achhabra2/kqb-json-viewer#3]
The code is now handling the error when no KQB directory exists (or defaulting to present working directory), and providing command line error messages. :)

However, at least for Windows users running the .exe directly (not from command line), it provides no visible error message to the user telling them the directory or JSON files are missing.  It just quietly exists, making it appear to the user that the .exe is not working.

I'm guessing the majority of BGL users will be on Windows, and not running from the command line.  Recommend adding a GUI dialog message telling the user of the error.  

https://developer.fyne.io/api/v2.0/dialog/ looks like the way...but I don't know enough Go to implement.

**Comment by achhabra2** [comment]
Fixed in v0.1.1
