### ISSUE TITLE
Ignore corrupt JSON files

### ISSUE THREAD

**Issue by austinmroczek** [achhabra2/kqb-json-viewer#5]
If a corrupt JSON file is added, the app errors out.  I tried both an empty file, and a file with the last `}` removed.  

```txt
2021/03/29 11:35:01 Could not parse json file (C:\Users\Admin\AppData\LocalLow\Liquid Bit, LLC\Killer Queen Black\match-stats\corrupt.json).  Error: unexpected end of JSON input
exit status 1
```
(note:  you only get the filename in the error message with my latest PR)

Recommend trapping this error somehow, telling the user about the bad file, then ignoring it and continue to process the rest of the files in the directory.

**Comment by achhabra2** [comment]
Fixed in v0.1.1
